name: build-test-ubuntu-gcc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_GMOCK=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ./tests/build/test
