name: build-test-windows-msvc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_GMOCK=OFF -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -G "NMake Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: .\\tests\\build\\test.exe
